### ISSUE TITLE
error on npm install node-core-audio

### ISSUE THREAD

**Issue by airbone42** [ZECTBynmo/node-core-audio#27]
Hi,

when I try to install node-core-audio to my Debian instance I end up with "make failed with exit code: 2".

Before that I get a warning in AudioEngine.cpp:78:51 that argument 3 has to be type "long int", but "unsinged int" was used.

Is that a known problem? How can I fix it?

Regards,
Tobias.

**Comment by sarahwalters** [comment]
I'm encountering a very similar error trying to install node-core-audio. Was this ever resolved?
</br>
</br>
*Note: \<app-path\> represents the directory containing my project
</br>
$ npm install --save node-core-audio
 
\> streamws@0.1.1 install \<app-path\>/node_modules/node-core-audio/node_modules/audio-streamer/node_modules/binaryjs/node_modules/streamws
\> node install.js

[ws v0.1.1] Attempting to compile blazing fast native extensions.
[ws v0.1.1] Native extension compilation successful!

\> node-core-audio@0.4.1 install \<app-path\>/node_modules/node-core-audio
\> node-gyp rebuild

make: Entering directory `\<app-path\>/node_modules/node-core-audio/build'
  CXX(target) Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:0:
../NodeCoreAudio/AudioEngine.h: In constructor ‘Audio::AudioEngine::AudioEngine(v8::Local<v8::Object>)’:
../NodeCoreAudio/AudioEngine.h:110:11: warning: ‘Audio::AudioEngine::m_pLocker’ will be initialized after [-Wreorder]
   Locker* m_pLocker;
           ^
../NodeCoreAudio/AudioEngine.h:100:5: warning:   ‘bool Audio::AudioEngine::m_bOutputIsEmpty’ [-Wreorder]
     m_bOutputIsEmpty,
     ^
../NodeCoreAudio/AudioEngine.cpp:27:1: warning:   when initialized here [-Wreorder]
 Audio::AudioEngine::AudioEngine( Local<Object> options ) :
 ^
../NodeCoreAudio/AudioEngine.cpp: In member function ‘void Audio::AudioEngine::applyOptions(v8::Local<v8::Object>)’:
../NodeCoreAudio/AudioEngine.cpp:216:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < oldBufferCount; i++) {
                       ^
../NodeCoreAudio/AudioEngine.cpp: In member function ‘void Audio::AudioEngine::RunAudioLoop()’:
../NodeCoreAudio/AudioEngine.cpp:391:180: error: ‘memcpy’ was not declared in this scope
    memcpy(m_cachedOutputSampleBlockForWriting, m_cachedOutputSampleBlock[m_uCurrentReadBuffer], m_uNumCachedOutputSamples[m_uCurrentReadBuffer] * m_uOutputChannels * m_uSampleSize);
                                                                                                                                                                                    ^
../NodeCoreAudio/AudioEngine.cpp:406:11: error: ‘Sleep’ was not declared in this scope
    Sleep(1);
           ^
make: *** [Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o] Error 1
make: Leaving directory `\<app-path\>/node_modules/node-core-audio/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd \<app-path\>/node_modules/node-core-audio
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! node-core-audio@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-core-audio@0.4.1 install script.
npm ERR! This is most likely a problem with the node-core-audio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-core-audio
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--save" "node-core-audio"
npm ERR! cwd \<app-path\>
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by xseignard** [comment]
To install the lib on ubuntu, i had to do a little modification, see #41

**Comment by Chadtech** [comment]
Same problem on Mac OSX. It says the command that failed is node-gyp rebuild
