### ISSUE TITLE
Raspberry PI installation fails

### ISSUE THREAD

**Issue by jdfreder** [ZECTBynmo/node-core-audio#42]
Hi,

Like @ZECTBynmo suggests in https://github.com/ZECTBynmo/node-core-audio/issues/21, installing lib alsa solves part of the problems.

`sudo apt-get install libasound2-dev` 

I went ahead and installed PortAudio too.

However, there's another problem, maybe two.  One related to WebSocketServer.test.js and one to verror:

```
npm ERR! Error: ENOENT, lstat '/home/pi/myproject/node_modules/node-core-audio/node_modules/audio-streamer/node_modules/binaryjs/node_modules/streamws/test/WebSocketServer.test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-core-audio"
npm ERR! cwd /home/pi/myproject
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! path /home/pi/myproject/node_modules/node-core-audio/node_modules/audio-streamer/node_modules/binaryjs/node_modules/streamws/test/WebSocketServer.test.js
npm ERR! fstream_path /home/pi/myproject/node_modules/node-core-audio/node_modules/audio-streamer/node_modules/binaryjs/node_modules/streamws/test/WebSocketServer.test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: No compatible version found: verror@'^1.4.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.1.0","1.2.0","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.3.5","1.3.6","1.3.7","1.4.0","1.5.0","1.5.1","1.6.0"]
npm ERR!     at installTargetsError (/home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/home/pi/node-v0.10.2-linux-arm-pi/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-core-audio"
npm ERR! cwd /home/pi/myproject
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
```

Any help would be appreciated, thanks!

**Comment by jdfreder** [comment]
False alarm!  Upgrading npm fixed the problem, sorry for the noise!
