### ISSUE TITLE
Installation fails for node-v5.1.0

### ISSUE THREAD

**Issue by AlexanderHolzer** [ZECTBynmo/node-core-audio#56]
Hi, I am still having issues when installing node-core-audio.

This is the error:
```javascript
CXX(target) Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
In file included from /Users/user/Dev/nodejs/SoundCast/Desktop/nodeshout-master/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:11:
/Users/user/.node-gyp/4.2.2/include/node/node_internals.h:6:10: fatal error: 
      'util-inl.h' file not found
#include "util-inl.h"
         ^
1 error generated.
make: *** [Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node4-lts/4.2.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Dev/nodejs/SoundCast/Desktop/nodeshout-master/node_modules/node-core-audio
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.2.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-core-audio@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-core-audio@0.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-core-audio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-core-audio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Dev/nodejs/SoundCast/Desktop/nodeshout-master/demos/npm-debug.log
```

I tried updated nan to v2.1.0, but that does still not solve my issue.
Any hints?

Thx, Alex

**Comment by kingdido999** [comment]
I'm having the same error with node v5.6.0 and npm v3.6.0.

**Comment by helio-frota** [comment]
+1 here

fatal error: util.h: No such file or directory

**Comment by mattp88** [comment]
+1 Not seeing any change through v5.11.0

**Comment by funwithtriangles** [comment]
Would love to see this fixed!

**Comment by bencmbrook** [comment]
Same error with node v4.4.4

**Comment by bomzj** [comment]
The error persists:
```
C:\Temp\Node>npm install node-core-audio

> streamws@0.1.1 install C:\Temp\Node\node_modules\streamws
> node install.js

[ws v0.1.1] Attempting to compile blazing fast native extensions.
[ws v0.1.1] Native code compile failed (but the module will still work):
[ws v0.1.1] The native extensions are faster, but not required.
[ws v0.1.1] On Windows, native extensions require Visual Studio and Python.
[ws v0.1.1] On Unix, native extensions require Python, make and a C++ compiler.
[ws v0.1.1] Start npm with --ws:verbose to show compilation output (if any).

> node-core-audio@0.5.1 install C:\Temp\Node\node_modules\node-core-audio
> node-gyp rebuild


C:\Temp\Node\node_modules\node-core-audio>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Temp\Node\node_modules\node-core-audio
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
```
