### ISSUE TITLE
Install build fails due to not finding node_internals.h

### ISSUE THREAD

**Issue by carsonk** [ZECTBynmo/node-core-audio#66]
When trying to install node-core-audio, the build fails with the following:

> streamws@0.1.1 install /home/carson/Projects/cueninja/node_modules/streamws
> node install.js
> 
> [ws v0.1.1] Attempting to compile blazing fast native extensions.
> [ws v0.1.1] Native code compile failed (but the module will still work):
> [ws v0.1.1] The native extensions are faster, but not required.
> [ws v0.1.1] On Windows, native extensions require Visual Studio and Python.
> [ws v0.1.1] On Unix, native extensions require Python, make and a C++ compiler.
> [ws v0.1.1] Start npm with --ws:verbose to show compilation output (if any).
> 
> node-core-audio@0.5.0 install /home/carson/Projects/cueninja/node_modules/node-core-audio
> node-gyp rebuild
> 
> make: Entering directory '/home/carson/Projects/cueninja/node_modules/node-core-audio/build'
>   CXX(target) Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o
> In file included from ../NodeCoreAudio/AudioEngine.cpp:9:0:
> ../NodeCoreAudio/AudioEngine.h:11:28: fatal error: node_internals.h: No such file or directory
>  #include <node_internals.h>
>                             ^
> compilation terminated.
> NodeCoreAudio.target.mk:93: recipe for target 'Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o' failed
> make: *** [Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o] Error 1
> make: Leaving directory '/home/carson/Projects/cueninja/node_modules/node-core-audio/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> gyp ERR! System Linux 3.16.0-4-amd64
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/carson/Projects/cueninja/node_modules/node-core-audio
> gyp ERR! node -v v6.2.1
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok 
> npm WARN cueninja@0.1.0 No description
> npm WARN cueninja@0.1.0 No repository field.
> npm WARN cueninja@0.1.0 No license field.
> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-core-audio"
> npm ERR! node v6.2.1
> npm ERR! npm  v3.9.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-core-audio@0.5.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-core-audio@0.5.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the node-core-audio package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-core-audio
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls node-core-audio
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/carson/Projects/cueninja/npm-debug.log

Let me know if I am doing something incorrectly.

**Comment by bencmbrook** [comment]
The npm version isn't up to date. Get the master branch and install that instead for now. Just go to your package.json and add `"node-core-audio": "ZECTBynmo/node-core-audio"` as a dependency and then npm install that.
