### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by bencmbrook** [ZECTBynmo/node-core-audio#67]
I managed to install the master branch but am now getting the following version mismatch error:

```
Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at new AudioEngine (/Users/benbrook/Code.noindex/bpm2/bpmv2/node_modules/node-core-audio/node-core-audio.js:36:24)
```

**Comment by bencmbrook** [comment]
If I update Node to v6 this works, but shouldn't this work with other versions as well?

**Comment by chinaguo** [comment]
> electron .

App threw an error during load
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at new AudioEngine (/Users/guoxinchun1/project/nodejs/electron/electron-quick-start/node_modules/node-core-audio/node-core-audio.js:36:24)

I have already updated Node to v6 my works, but the issue occured.Is there any other way？Thanks

**Comment by chinaguo** [comment]
Furthermore， I used electron.

**Comment by hugohil** [comment]
Hi @chinaguo, have you tried this ?

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

Hope this helps :)

**Comment by bencmbrook** [comment]
Yes, thanks @hugohil I got it working by using the Github version, which I think was slightly different from the npm version.
